// Translate VN-prefix tx notes auto-generated by bill pay + transfer.
// User-typed notes pass through unchanged.
import { t } from './index';

export function displayTxNote(note: string | null | undefined): string {
  if (!note) return '';
  if (note.startsWith('Chuyển →')) {
    const rest = note.slice('Chuyển →'.length).trim();
    return rest ? `${t('tx.transferOut')} ${rest}` : t('tx.transferOut');
  }
  if (note.startsWith('Nhận ←')) {
    const rest = note.slice('Nhận ←'.length).trim();
    return rest ? `${t('tx.transferIn')} ${rest}` : t('tx.transferIn');
  }
  if (note.startsWith('Hoá đơn ')) {
    const billName = note.slice('Hoá đơn '.length);
    return t('tx.billLabel', { name: billName });
  }
  return note;
}
